import path from "node:path";
import { realpath } from "node:fs/promises";
import { homedir } from "node:os";

import {
  MANIFEST_FILE_NAME,
  PRIMARY_ROOT_PLACEHOLDER,
  describeOperations,
  readManifest,
} from "./manifest.mjs";
import { defaultRuntimeRoot, loadPolicy, loadRegistry, policyPathFor } from "./registry.mjs";
import { execFile, pathExists, requirePrimaryCheckout } from "./cli-host.mjs";
import { CliError } from "./cli-arguments.mjs";

export async function commandList(options) {
  const runtimeRoot = options.values["runtime-root"]
    ? path.resolve(options.values["runtime-root"])
    : defaultRuntimeRoot();
  const registry = await loadRegistry(runtimeRoot);
  const rows = [...registry.policies.values()].map((policy) => ({
    projectId: policy.projectId,
    hostId: policy.trustedHostId,
    primaryRoot: policy.primaryRoot,
    composeProject: policy.composeProject ?? null,
    containers: policy.containers,
    manifestStale: policy.manifestStale,
    manifestError: policy.manifestError,
  }));
  if (options.flags.has("json")) {
    process.stdout.write(`${JSON.stringify({ projects: rows, problems: registry.problems }, null, 2)}\n`);
    return;
  }
  if (rows.length === 0) {
    process.stdout.write("No projects are registered on this host.\n");
  }
  for (const row of rows) {
    process.stdout.write(
      `${row.projectId}  ${row.primaryRoot}  compose=${row.composeProject ?? "-"}  ${row.manifestError ? `manifest error: ${row.manifestError}` : row.manifestStale ? "manifest changed (run sync)" : "ok"}\n`,
    );
  }
  for (const problem of registry.problems) {
    process.stdout.write(`skipped ${problem.path}: ${problem.message}\n`);
  }
}

export async function commandValidate(options) {
  const { primaryRoot } = await requirePrimaryCheckout(process.cwd()).catch(async () => ({
    primaryRoot: await realpath(process.cwd()),
  }));
  const loaded = await readManifest(primaryRoot);
  const operations = describeOperations(loaded.manifest);
  if (options.flags.has("json")) {
    process.stdout.write(
      `${JSON.stringify(
        {
          digest: loaded.digest,
          containers: Object.keys(loaded.manifest.containers),
          operations,
          lifecycle: Object.keys(loaded.manifest.lifecycle),
        },
        null,
        2,
      )}\n`,
    );
    return;
  }
  process.stdout.write(`${loaded.path} is valid (sha256 ${loaded.digest.slice(0, 12)}).\n`);
  process.stdout.write(`Containers: ${Object.keys(loaded.manifest.containers).join(", ")}\n`);
  process.stdout.write(`Lifecycle: ${Object.keys(loaded.manifest.lifecycle).join(", ") || "-"}\n`);
  process.stdout.write(`Operations:\n${operations.map((line) => `  ${line}`).join("\n")}\n`);
}

export async function commandEnv() {
  const { primaryRoot } = await requirePrimaryCheckout(process.cwd());
  const worktreeRoot = path.resolve(
    process.env.BB_WORKTREES_ROOT ?? path.join(homedir(), ".bb", "worktrees"),
  );
  process.stdout.write(`export BB_WORKTREES_ROOT=${JSON.stringify(worktreeRoot)}\n`);
  process.stdout.write(`export BB_PRIMARY_ROOT=${JSON.stringify(primaryRoot)}\n`);
}

export async function commandComposeOverlay() {
  const primaryRoot = await realpath(process.cwd());
  const loaded = await readManifest(primaryRoot);
  const manifest = loaded.manifest;
  const lines = [
    `# Generated by bb-shared-runtime compose-overlay from ${MANIFEST_FILE_NAME}.`,
    "# Apply with: docker compose -f <main compose file> -f <this file> ...",
    "# Source the output of `bb-shared-runtime env` first.",
    "services:",
  ];
  for (const [, container] of Object.entries(manifest.containers)) {
    lines.push(`  ${container.service}:`);
    lines.push("    volumes:");
    lines.push(
      `      - \${BB_WORKTREES_ROOT:?BB_WORKTREES_ROOT must be set}:${manifest.worktrees.containerRoot}`,
    );
    if (container.mounts.some((mount) => mount.container === PRIMARY_ROOT_PLACEHOLDER)) {
      lines.push(
        "      - ${BB_WORKTREES_ROOT:?BB_WORKTREES_ROOT must be set}:${BB_WORKTREES_ROOT:?BB_WORKTREES_ROOT must be set}",
      );
      lines.push(
        "      - ${BB_PRIMARY_ROOT:?BB_PRIMARY_ROOT must be set}:${BB_PRIMARY_ROOT:?BB_PRIMARY_ROOT must be set}",
      );
    }
    for (const mount of container.mounts) {
      if (mount.container === PRIMARY_ROOT_PLACEHOLDER) {
        continue;
      }
      const hostPath = mount.host === "." ? "${BB_PRIMARY_ROOT:?BB_PRIMARY_ROOT must be set}" : `\${BB_PRIMARY_ROOT:?BB_PRIMARY_ROOT must be set}/${mount.host}`;
      lines.push(`      - ${hostPath}:${mount.container}`);
    }
  }
  process.stdout.write(`${lines.join("\n")}\n`);
}

async function inspectMounts(dockerPath, container) {
  const { stdout } = await execFile(dockerPath, [
    "inspect",
    "--format",
    "{{json .Mounts}}",
    container,
  ]);
  return JSON.parse(stdout);
}

async function noteWorktreeMount(note, policy, role, source) {
  const worktreeRoot = policy.manifest.worktrees.containerRoot;
  let resolved = source;
  try {
    resolved = await realpath(source);
  } catch {
    // Keep the unresolved source path.
  }
  note(
    resolved === (await realpath(policy.worktreeRoot).catch(() => policy.worktreeRoot)) || source === policy.worktreeRoot
      ? "ok"
      : "warn",
    `container ${role}: ${worktreeRoot} is mounted from ${source}`,
  );
}

async function checkContainerMounts(policy, role, name, primaryRoot, note) {
  let mounts;
  try {
    mounts = await inspectMounts(policy.dockerPath, name);
  } catch {
    note("error", `container ${role} (${name}) is not running or not created`);
    return;
  }
  const destinations = new Map(
    mounts.map((mount) => [mount.Destination, mount.Source ?? mount.Name ?? ""]),
  );
  const worktreeRoot = policy.manifest.worktrees.containerRoot;
  if (destinations.has(worktreeRoot)) {
    await noteWorktreeMount(note, policy, role, destinations.get(worktreeRoot));
  } else {
    note("error", `container ${role} (${name}) does not mount ${worktreeRoot}`);
  }
  for (const mount of policy.manifest.containers[role].mounts) {
    const expected = mount.container === PRIMARY_ROOT_PLACEHOLDER ? primaryRoot : mount.container;
    if (!destinations.has(expected)) {
      note("error", `container ${role} (${name}) does not mount ${mount.host} at ${expected}`);
    }
  }
  if (policy.manifest.containers[role].mounts.some((mount) => mount.container === PRIMARY_ROOT_PLACEHOLDER) && !destinations.has(policy.worktreeRoot)) {
    note(
      "error",
      `container ${role} (${name}) must also mount ${policy.worktreeRoot} at the identical path for Git worktree metadata`,
    );
  }
}

async function checkPolicy(policy, primaryRoot, runtimeRoot, note) {
  note("ok", `registration ${policy.projectId} on host ${policy.trustedHostId}`);
  if (policy.manifestError) {
    note("error", `manifest: ${policy.manifestError}`);
    return;
  }
  if (policy.manifestStale) {
    note("error", "manifest changed since installation; run bb-shared-runtime sync");
  } else {
    note("ok", `manifest hash ${policy.manifestSha256.slice(0, 12)} matches`);
  }
  const loadedPolicy = await loadPolicy(policyPathFor(policy.projectId, runtimeRoot)).catch((error) => {
    note("error", `policy file: ${error.message}`);
    return null;
  });
  if (loadedPolicy) {
    note("ok", "policy file permissions verified");
  }
  const launcher = path.join(primaryRoot, ".bb-runtime", "landlock-run");
  note(
    (await pathExists(launcher)) ? "ok" : "warn",
    (await pathExists(launcher))
      ? "isolation launcher is built"
      : "isolation launcher not built yet (built on first quality operation)",
  );
  for (const [role, name] of Object.entries(policy.containers)) {
    await checkContainerMounts(policy, role, name, primaryRoot, note);
  }
}

export async function commandDoctor(options) {
  const runtimeRoot = options.values["runtime-root"]
    ? path.resolve(options.values["runtime-root"])
    : defaultRuntimeRoot();
  const { primaryRoot } = await requirePrimaryCheckout(process.cwd());
  const registry = await loadRegistry(runtimeRoot);
  const candidates = [...registry.policies.values()].filter(
    (policy) => policy.primaryRoot === primaryRoot,
  );
  const findings = [];
  const note = (level, message) => findings.push({ level, message });
  if (candidates.length === 0) {
    note("error", `no registration for ${primaryRoot}; run bb-shared-runtime install`);
  }
  for (const policy of candidates) {
    await checkPolicy(policy, primaryRoot, runtimeRoot, note);
  }
  if (options.flags.has("json")) {
    process.stdout.write(`${JSON.stringify({ findings }, null, 2)}\n`);
  } else {
    for (const finding of findings) {
      process.stdout.write(`${finding.level.padEnd(5)} ${finding.message}\n`);
    }
  }
  if (findings.some((finding) => finding.level === "error")) {
    throw new CliError("doctor found errors", 1);
  }
}
